name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Check app
        run: ./gradlew :app:check

      - name: Run Dectkt
        run: ./gradlew dectkt

#      - name: Report warring to git hub
#        run: |
#          echo Set Permission
#          sh -c "sudo chmod -R 777 scripts/saddler.sh"
#          echo run scripts
#          scripts/saddler.sh
